services:
  app:
    build:
      context: ./container/app/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./container/app/src:/usr/src
      - node_data:/src/node_modules
    tty: true
    #command: npm run dev

volumes:
  node_data:
